Revert "Add --apply-only to benchmarks"
This reverts commit f50f73f962667807951e66b2aecd5a86bdb47a87.

Reason for revert: Breaks all benchmarks on ci with `AttributeError: 'Options' object has no attribute 'apply_only'. Did you mean: 'ApplyOnly'?`

Change-Id: I060cb40901a9ea348c80c24d6d9bf574545ce36f