Revert "Reapply "Export pvmfw properties to soong""
Revert submission 34152492-reapply_pvmfw_soong

Reason for revert: Breaks brya and nissa builds (ab/git_main-throttled). For example: http://ab/13682614

```
error: build/soong/fsgen/Android.bp:32:1: module "brya_generated_device" variant "android_x86_64_alderlake" (created by module "soong_filesystem_creator" variant "android_common"): depends on disabled module "pvmfw_img"
```

Reverted changes: /q/submissionid:34152492-reapply_pvmfw_soong

Change-Id: I09e462bf89b446be5f60eea42283fd0c32c819eb